### PR TITLE
Makefile: Use latexmk instead of xelatex directly

### PR DESCRIPTION
**Pull request by auscompgeek**

### CODE REVIEW

**Comment by thewrongjames** [comment]
That is the reason for / benefit of this change?

**Comment by auscompgeek** [comment]
latexmk loops the LaTeX compiler for precisely the number of times required to recompile. If the toc doesn't change then the second run would've been redundant.

**Comment by auscompgeek** [comment]
Also newer versions of latexmk avoid the redundant intermediate PDF when you need to loop (doesn't look like the version in Ubuntu 18.04 does though).

**Review by thewrongjames — APPROVED** [review]
This is good and should have been merged ages ago. Sorry.

**Pull request merged**
