### PR TITLE
Fix count of further exec (4.1.12)

### PR DESCRIPTION
**Pull request by auscompgeek**

### CODE REVIEW

**Comment by thewrongjames** [comment]
@lstua @brad-rego this is technically an actually change to the constitution, if only to fix a small error. Could this be allowed at the upcoming GM?

**Comment by auscompgeek** [comment]
This was already submitted in writing directly to the secretary.

**Comment by brad-rego** [comment]
@thewrongjames we cant push until it's voted through at the gm

**Comment by thewrongjames** [comment]
It seems that this has been made redundant by the updates from the GM (even though this was proposed towards it), because the GM increased the number of industry liasons to 3, making this typo correct. Not sure how those changes are going to end up in the constitution on here though as until the GM I hadn't seen any sign of those changes...

**Comment by thewrongjames** [comment]
Guess I should look into that.

**Comment by auscompgeek** [comment]
Honestly, I never received the meeting link…

**Comment by thewrongjames** [comment]
I got it through Facebook. I don't know if it was ever anywhere else. It seems that Sonia is indeed planning to write up the amendments as a PR to this report though.

**Pull request closed without merging**
